// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(CarsDBContext))]
    [Migration("20260629204700_adding_price_column")]
    partial class adding_price_column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Car", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fuelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("hp")
                        .HasColumnType("int");

                    b.Property<int>("km")
                        .HasColumnType("int");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("manufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("transmissionType")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("vehicleType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            id = new Guid("11111111-1111-1111-1111-111111111111"),
                            fuelType = "Benzin",
                            hp = 122,
                            km = 167000,
                            manufacturer = "Audi",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "A4",
                            price = 0.0,
                            transmissionType = "Automatic",
                            vehicleType = "Limousine"
                        },
                        new
                        {
                            id = new Guid("22222222-2222-2222-2222-222222222222"),
                            fuelType = "Benzin",
                            hp = 96,
                            km = 235000,
                            manufacturer = "Volkswagen",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "Golf",
                            price = 0.0,
                            transmissionType = "Automatic",
                            vehicleType = "Compact"
                        },
                        new
                        {
                            id = new Guid("33333333-3333-3333-3333-333333333333"),
                            fuelType = "Benzin",
                            hp = 150,
                            km = 35000,
                            manufacturer = "Formentor",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "Cupra",
                            price = 0.0,
                            transmissionType = "Automatic",
                            vehicleType = "SUV"
                        },
                        new
                        {
                            id = new Guid("44444444-4444-4444-4444-444444444444"),
                            fuelType = "Benzin",
                            hp = 155,
                            km = 27000,
                            manufacturer = "Karoq",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "Skoda",
                            price = 0.0,
                            transmissionType = "Automatic",
                            vehicleType = "SUV"
                        },
                        new
                        {
                            id = new Guid("55555555-5555-5555-5555-555555555555"),
                            fuelType = "Benzin",
                            hp = 245,
                            km = 123000,
                            manufacturer = "M4",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "BWM",
                            price = 0.0,
                            transmissionType = "Automatic",
                            vehicleType = "Coupé"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
