// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(CarDealerDbContext))]
    [Migration("20260825204539_Reworking Status Column at Reservation table")]
    partial class ReworkingStatusColumnatReservationtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Car", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fuelType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("hp")
                        .HasColumnType("int");

                    b.Property<int>("km")
                        .HasColumnType("int");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("manufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("transmissionType")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("vehicleType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            id = new Guid("11111111-1111-1111-1111-111111111111"),
                            fuelType = "Benzin",
                            hp = 122,
                            km = 167000,
                            manufacturer = "Audi",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "A4",
                            price = 0m,
                            transmissionType = "Automatic",
                            vehicleType = "Limousine"
                        },
                        new
                        {
                            id = new Guid("22222222-2222-2222-2222-222222222222"),
                            fuelType = "Benzin",
                            hp = 96,
                            km = 235000,
                            manufacturer = "Volkswagen",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "Golf",
                            price = 0m,
                            transmissionType = "Automatic",
                            vehicleType = "Compact"
                        },
                        new
                        {
                            id = new Guid("33333333-3333-3333-3333-333333333333"),
                            fuelType = "Benzin",
                            hp = 150,
                            km = 35000,
                            manufacturer = "Formentor",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "Cupra",
                            price = 0m,
                            transmissionType = "Automatic",
                            vehicleType = "SUV"
                        },
                        new
                        {
                            id = new Guid("44444444-4444-4444-4444-444444444444"),
                            fuelType = "Benzin",
                            hp = 155,
                            km = 27000,
                            manufacturer = "Karoq",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "Skoda",
                            price = 0m,
                            transmissionType = "Automatic",
                            vehicleType = "SUV"
                        },
                        new
                        {
                            id = new Guid("55555555-5555-5555-5555-555555555555"),
                            fuelType = "Benzin",
                            hp = 245,
                            km = 123000,
                            manufacturer = "M4",
                            manufacturingDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            model = "BWM",
                            price = 0m,
                            transmissionType = "Automatic",
                            vehicleType = "Coupé"
                        });
                });

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            id = new Guid("11111111-1111-1111-1111-111111111111"),
                            address = "asd str. 8A",
                            birthDate = new DateTime(2000, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "asd@gmail.com",
                            firstName = "Ella",
                            lastName = "Nut",
                            phoneNumber = "064581306841"
                        },
                        new
                        {
                            id = new Guid("22222222-2222-2222-2222-222222222222"),
                            address = "asd str. 10A",
                            birthDate = new DateTime(2013, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "asd@gmail.at",
                            firstName = "Elek",
                            lastName = "Mek",
                            phoneNumber = "064581306976"
                        },
                        new
                        {
                            id = new Guid("33333333-3333-3333-3333-333333333333"),
                            address = "asd str. 26A",
                            birthDate = new DateTime(1986, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "asd@gmail.eu",
                            firstName = "Edda",
                            lastName = "Kor",
                            phoneNumber = "064581300123"
                        });
                });

            modelBuilder.Entity("Entities.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Entities.Reservation", b =>
                {
                    b.HasOne("Entities.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Entities.Car", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
